[phases.setup]
nixPkgs = ["ffmpeg", "python3"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["NEXT_DISABLE_TURBOPACK=1 npm run build"]

[start]
cmds = ["bash", "-lc", "which ffmpeg && ffmpeg -version && npm run start"]
