[phases.setup]
nixPkgs = ["ffmpeg", "python3"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "which ffmpeg",
  "which ffprobe",
  "npm run build"
]

[start]
cmd = "bash -lc 'which ffmpeg && ffmpeg -version && npm run start'"

